import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--enable-unsafe-swiftshader'] });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
await ctx.addInitScript(() => { sessionStorage.setItem('loaderSeen', '1'); });
const p = await ctx.newPage();
await p.goto('http://localhost:4175/', { waitUntil: 'networkidle' });
await p.waitForTimeout(800);
await p.keyboard.press('Tab');
console.log('1er Tab →', await p.evaluate(() => document.activeElement.className + ' | ' + document.activeElement.textContent?.slice(0, 30)));
for (let i = 0; i < 5; i++) await p.keyboard.press('Tab');
console.log('6e Tab →', await p.evaluate(() => document.activeElement.textContent?.slice(0, 30)));
await p.keyboard.press('Control+k');
await p.waitForTimeout(400);
console.log('Ctrl+K → focus:', await p.evaluate(() => document.activeElement.className));
await p.keyboard.press('Tab');
console.log('Tab dans palette → focus reste:', await p.evaluate(() => document.activeElement.className));
await p.keyboard.press('ArrowDown');
await p.keyboard.press('Enter');
await p.waitForTimeout(1200);
console.log('Entrée sur 2e item → scroll vers:', await p.evaluate(() => Math.round(window.scrollY)));
await browser.close();
