name: Generate Daily Blog Post

on:

  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache models
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: models-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Fetch items
        run: node scripts/generate-blog.mjs
      - name: Enrich articles
        run: npm run enrich-blog
      - name: Generate blog
        run: node scripts/generate-blog.mjs
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '📰 chore(blog): Update daily radar'
          file_pattern: "blog blog_meta .cache"
